# Generated by Django 6.1.1 on 2026-09-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_lesson_subsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
